//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestMSMQ.MVCApp___WCF.MVCApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paymessage
    {
        public int id { get; set; }
        public System.Guid EventId { get; set; }
        public string error { get; set; }
        public string state { get; set; }
    }
}
