//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class nservicebusEntities : DbContext
    {
        public nservicebusEntities()
            : base("name=nservicebusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<audit> audits { get; set; }
        public DbSet<error> errors { get; set; }
        public DbSet<MyPublisher> MyPublishers { get; set; }
        public DbSet<MyPublisher_Retries> MyPublisher_Retries { get; set; }
        public DbSet<MyPublisher_Timeouts> MyPublisher_Timeouts { get; set; }
        public DbSet<MyPublisher_TimeoutsDispatcher> MyPublisher_TimeoutsDispatcher { get; set; }
        public DbSet<Subscriber1> Subscriber1 { get; set; }
        public DbSet<Subscriber1_Retries> Subscriber1_Retries { get; set; }
        public DbSet<Subscriber1_Timeouts> Subscriber1_Timeouts { get; set; }
        public DbSet<Subscriber1_TimeoutsDispatcher> Subscriber1_TimeoutsDispatcher { get; set; }
        public DbSet<Subscriber2> Subscriber2 { get; set; }
        public DbSet<Subscriber2_Retries> Subscriber2_Retries { get; set; }
        public DbSet<Subscriber2_Timeouts> Subscriber2_Timeouts { get; set; }
        public DbSet<Subscriber2_TimeoutsDispatcher> Subscriber2_TimeoutsDispatcher { get; set; }
        public DbSet<Subscription> Subscriptions { get; set; }
    }
}
