//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestHandlers.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://nservicebus.com", ConfigurationName="ServiceReference1.IWcfServiceOf_PayMessage_ErrorCodes")]
    public interface IWcfServiceOf_PayMessage_ErrorCodes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nservicebus.com/IWcfServiceOf_PayMessage_ErrorCodes/Process", ReplyAction="http://nservicebus.com/IWcfServiceOf_PayMessage_ErrorCodes/ProcessResponse")]
        Messages.ErrorCodes Process(MyMessages.IMessages.PayMessage request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nservicebus.com/IWcfServiceOf_PayMessage_ErrorCodes/Process", ReplyAction="http://nservicebus.com/IWcfServiceOf_PayMessage_ErrorCodes/ProcessResponse")]
        System.Threading.Tasks.Task<Messages.ErrorCodes> ProcessAsync(MyMessages.IMessages.PayMessage request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceOf_PayMessage_ErrorCodesChannel : UnitTestHandlers.ServiceReference1.IWcfServiceOf_PayMessage_ErrorCodes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceOf_PayMessage_ErrorCodesClient : System.ServiceModel.ClientBase<UnitTestHandlers.ServiceReference1.IWcfServiceOf_PayMessage_ErrorCodes>, UnitTestHandlers.ServiceReference1.IWcfServiceOf_PayMessage_ErrorCodes {
        
        public WcfServiceOf_PayMessage_ErrorCodesClient() {
        }
        
        public WcfServiceOf_PayMessage_ErrorCodesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceOf_PayMessage_ErrorCodesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceOf_PayMessage_ErrorCodesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceOf_PayMessage_ErrorCodesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Messages.ErrorCodes Process(MyMessages.IMessages.PayMessage request) {
            return base.Channel.Process(request);
        }
        
        public System.Threading.Tasks.Task<Messages.ErrorCodes> ProcessAsync(MyMessages.IMessages.PayMessage request) {
            return base.Channel.ProcessAsync(request);
        }
    }
}
